### ISSUE TITLE
Iomrascalai passes when it shouldn't

### ISSUE THREAD

**Issue by iopq** [ujh/iomrascalai#261]
[weird case.zip](https://github.com/ujh/iomrascalai/files/146464/weird.case.zip)

Here it should take the ko, white is dead if that happens, but it passes instead
Older versions do not do this

**Comment by ujh** [comment]
I saw some of these as well. If you run the bot inside of Gogui with the `--gfx` flag turned on you will see that it passes once all intersections on the board belong (as defined by that intersection being counted as territory for one color most of the time) to either black or white.

The easy solution is to never pass early, but it would be nice to find a better solution when playing against human opponents.

**Comment by ujh** [comment]
Once I'm done with the speed up of the board I'll have a look at this. A possible solution would be to allow playing pass moves once all intersections are decided. That is, instead of *always* playing a pass just pick the best move but this time include the pass move. 

That approach is probably equivalent to playing until the bitter end so many a better approach would be to play a pass if it's winning percentage is close to the best move. We'll see.

**Comment by iopq** [comment]
Speeding up the playouts is not urgent, IMO. There's very little difference between playing strength of Iomrascalai even when it gets two times more thinking time. This bug makes it lose way more than any inefficiency.

**Comment by ujh** [comment]
I'll have a look at it next week. On 9x9 or 13x13 that bug is certainly worse than any inefficiency in the code. For 19x19 I'm not so sure, but I guess it's still a long way until we can beat GnuGo on 19x19.
